### ISSUE TITLE
Fix for your "Load Issues"

### ISSUE THREAD

**Issue by KMFDManic** [markwkidd/FreeIntv#2]
@markwkidd 

I see you've been having troublesome woes with the FreeIntv.  I work with Cores for the NES Classic/SNES Classic, and I definitely wanted to get this running pronto!  Myself and a very good Coding Friend, madmonkey looked into fixing things up.  Madmonkey has this info, which I can fully confirm works!  I am running it, and will be releasing it into my Core Set, for next release...as well as posting a video of it in action:)  I will credit you and the original coder in my ReadMe:)  Hope this helps!  It will work on Windows, too:)

For the record, many games work quite nicely!  I am liking the very decent compatibility!  And, the control configuration works great for the SNES and Up Controller!

  -strcat(execPath, "exec.bin");
  -//printf("%s\n", execPath);
  +strcat(execPath, "/exec.bin");^M
  +printf("%s\n", execPath);^M

if path is /path/ it works
but if it's /path it doesn't work

in most cases
fopen/CreateFile will work, so command-line apps might not, but this doesn't use command-line interface

**Comment by markwkidd** [comment]
Thanks this is very helpful, I've incorporated your change and now I can load Astrosmash via RetroArch in Windows 7!

**Comment by KMFDManic** [comment]
@markwkidd 

Love the way you did the control scheme.  The keypad definitely needs done for ColecoVision (BlueMSX), and Atari 5200 (Atari 800)!!! 
 
You should definitely do a pull request to have that as an option:)  Not everyone has a keyboard:)

SNES Classic - Mattel Intellivision Test:)  

https://www.youtube.com/watch?v=ZRiJPmizklQ

I officially released the Core for use on NESC/SNESC on my github.

Huge thanks go to madmonkey for helping fix your coding conflict:)
